# Generated by Django 3.1 on 2020-08-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
